//
// Created by Artur on 09.01.2018.
//

#ifndef PRODUCTIONLINE_SIM_RECEIVERTYPE_H
#define PRODUCTIONLINE_SIM_RECEIVERTYPE_H


enum class ReceiverType {WORKER, STOREHOUSE};


#endif //PRODUCTIONLINE_SIM_RECEIVERTYPE_H
