//
// Created by bartek on 1/8/18.
//

#ifndef PRODUCTIONLINE_SIM_INTERVALREPORTNOTIFIER_H
#define PRODUCTIONLINE_SIM_INTERVALREPORTNOTIFIER_H


class IntervalReportNotifier {

};


#endif //PRODUCTIONLINE_SIM_INTERVALREPORTNOTIFIER_H
