//
// Created by bartek on 1/8/18.
//

#ifndef PRODUCTIONLINE_SIM_IPACKAGERECEIVER_H
#define PRODUCTIONLINE_SIM_IPACKAGERECEIVER_H


class IPackageReceiver {

};


#endif //PRODUCTIONLINE_SIM_IPACKAGERECEIVER_H
